/* characters.js
 * Original fighter roster. All names, moves, art direction and lore are
 * original creations — no relation to any existing game's characters.
 * Each entry drives both gameplay stats and the procedural canvas art
 * (see drawFighter() in effects.js) so every fighter reads as visually
 * distinct even though no external image/sprite assets are used.
 */

const CHARACTERS = {

  vela: {
    id: "vela",
    name: "VELA",
    title: "The Stormbringer",
    age: 24,
    style: "Storm-Step Martial Arts",
    personality: "Restless, playful, always moving. Talks trash mid-combo.",
    backstory: "Raised on a wind-swept coastal cliff, Vela trained by racing lightning storms down the mountain. She fights the way weather moves — sudden, unpredictable, gone before you can react.",
    outfit: "Cropped indigo battle-jacket with torn sleeves, fingerless gloves, storm-cloud embroidery.",
    palette: { primary: "#5ad1ff", secondary: "#1c2b4a", accent: "#eafcff", skin: "#e8b48a" },
    build: { height: 0.95, width: 0.82 }, // relative silhouette scale
    stats: { health: 90, power: 62, defense: 48, speed: 98, jump: 90, combo: 92, special: 80 },
    difficulty: "Medium",
    moves: {
      lightPunch: { name: "Snap Jab", dmg: 4 },
      heavyPunch: { name: "Cross Bolt", dmg: 9 },
      lightKick: { name: "Wind Flick", dmg: 5 },
      heavyKick: { name: "Gale Crescent", dmg: 10 },
    },
    specials: [
      { name: "Storm Dash", cost: 25, dmg: 12, type: "dash", desc: "Rockets forward wrapped in an electric trail." },
      { name: "Thunder Kick", cost: 30, dmg: 15, type: "strike", desc: "A rising kick crackling with voltage." },
      { name: "Tempest Combo", cost: 40, dmg: 20, type: "combo", desc: "A 4-hit flurry ending in a spinning heel drop." },
    ],
    ultimate: { name: "Eye of the Storm", dmg: 34, desc: "Vela vanishes into a localized cyclone and strikes from every angle at once." },
    victoryQuote: "Too slow. The storm doesn't wait.",
    defeatQuote: "Ugh... even lightning strikes out sometimes.",
    animStyle: "snappy, high-frequency, low commitment",
  },

  thrax: {
    id: "thrax",
    name: "THRAX",
    title: "Ironwall",
    age: 37,
    style: "Foundry Grappling",
    personality: "Calm, patient, almost gentle outside the ring. A wall of a man who rarely raises his voice.",
    backstory: "A former dock foreman who fought in unlicensed strength contests to pay off his crew's debts. He never lost a single one — nobody could move him.",
    outfit: "Sleeveless canvas work-vest over wrapped forearms, heavy steel-toe boots, a scarred leather belt.",
    palette: { primary: "#c97b3d", secondary: "#3a2a1e", accent: "#ffd9a0", skin: "#8a5a3c" },
    build: { height: 1.12, width: 1.25 },
    stats: { health: 130, power: 95, defense: 90, speed: 38, jump: 45, combo: 40, special: 55 },
    difficulty: "Easy",
    moves: {
      lightPunch: { name: "Jab Press", dmg: 5 },
      heavyPunch: { name: "Iron Smash", dmg: 13 },
      lightKick: { name: "Shin Check", dmg: 6 },
      heavyKick: { name: "Ground Breaker", dmg: 14 },
    },
    specials: [
      { name: "Fang Charge", cost: 25, dmg: 14, type: "dash", desc: "A shoulder-first charge that shrugs off hits." },
      { name: "Anvil Grip", cost: 30, dmg: 18, type: "grab", desc: "Catches the opponent and slams them down." },
      { name: "Quake Stomp", cost: 40, dmg: 16, type: "aoe", desc: "Stomps the ground, sending a shockwave outward." },
    ],
    ultimate: { name: "Iron Devastation", dmg: 40, desc: "Thrax lifts his opponent overhead and drives them through the stage floor." },
    victoryQuote: "Nothing personal. You just picked the wrong wall to punch.",
    defeatQuote: "...Didn't see that coming. Respect.",
    animStyle: "heavy wind-ups, long recovery, unmissable tells",
  },

  nyssa: {
    id: "nyssa",
    name: "NYSSA",
    title: "Nightveil",
    age: 21,
    style: "Veil-Step Assassination Arts",
    personality: "Quiet, sarcastic, unreadable behind her half-mask. Enjoys unsettling louder opponents.",
    backstory: "Trained from childhood by a reclusive order that teaches fighters to move like rumor — seen for a second, then gone. Nyssa left the order to test herself in open competition.",
    outfit: "Charcoal wrap-tunic, asymmetric half-mask, segmented arm guards, no visible weapons.",
    palette: { primary: "#8b5cf6", secondary: "#181022", accent: "#d9c8ff", skin: "#c99a78" },
    build: { height: 0.9, width: 0.72 },
    stats: { health: 75, power: 55, defense: 35, speed: 95, jump: 100, combo: 88, special: 90 },
    difficulty: "Hard",
    moves: {
      lightPunch: { name: "Veil Jab", dmg: 4 },
      heavyPunch: { name: "Phantom Strike", dmg: 10 },
      lightKick: { name: "Silent Sweep", dmg: 5 },
      heavyKick: { name: "Night Blade Kick", dmg: 11 },
    },
    specials: [
      { name: "Shadow Step", cost: 20, dmg: 8, type: "dash", desc: "Blinks a short distance, reappearing with a strike." },
      { name: "Phantom Strike", cost: 30, dmg: 16, type: "strike", desc: "A near-invisible thrust that's almost impossible to see coming." },
      { name: "Night Blade", cost: 35, dmg: 18, type: "strike", desc: "A crossing double-slash from both sides." },
    ],
    ultimate: { name: "Dance of Shadows", dmg: 36, desc: "Nyssa splits into afterimages that surround and strike the opponent from every side." },
    victoryQuote: "You were fighting a shadow the whole time.",
    defeatQuote: "...Impressive. That won't happen twice.",
    animStyle: "minimal, blink-cut movement, few visible frames",
  },

  kobra: {
    id: "kobra",
    name: "KOBRA",
    title: "Silk Fist",
    age: 29,
    style: "Coiled-Form Kung Fu",
    personality: "Formal, disciplined, respectful even to rivals. Speaks like a teacher correcting a student.",
    backstory: "The senior student of a mountain dojo who left to prove that discipline beats flash. Every motion he makes is textbook-perfect.",
    outfit: "Traditional high-collar training tunic, sash belt, cloth wraps on hands and forearms.",
    palette: { primary: "#22c55e", secondary: "#0e2718", accent: "#eafff0", skin: "#e0b58f" },
    build: { height: 1.0, width: 0.88 },
    stats: { health: 100, power: 70, defense: 68, speed: 70, jump: 72, combo: 85, special: 65 },
    difficulty: "Medium",
    moves: {
      lightPunch: { name: "Coil Jab", dmg: 5 },
      heavyPunch: { name: "Serpent Fist", dmg: 11 },
      lightKick: { name: "Low Sweep", dmg: 6 },
      heavyKick: { name: "Rising Talon", dmg: 12 },
    },
    specials: [
      { name: "Coil Counter", cost: 25, dmg: 12, type: "counter", desc: "Braces and redirects the opponent's next hit back at them." },
      { name: "Serpent Chain", cost: 30, dmg: 16, type: "combo", desc: "A rapid 3-strike chain ending in a palm thrust." },
      { name: "Talon Rise", cost: 30, dmg: 14, type: "strike", desc: "A rising uppercut-kick with a long reach." },
    ],
    ultimate: { name: "Hundred Silk Strikes", dmg: 32, desc: "A blur of a hundred perfectly placed strikes in under two seconds." },
    victoryQuote: "Form is discipline. Discipline is victory.",
    defeatQuote: "I will study this loss. Well fought.",
    animStyle: "fluid, textbook, deliberate follow-through",
  },

  rex: {
    id: "rex",
    name: "REX",
    title: "Streetwise",
    age: 26,
    style: "Freeform Street Brawling",
    personality: "Loud, cocky, loves an audience. Improvises everything.",
    backstory: "Grew up fighting for bus fare in back-alley matches with no rules and no referees. Rex doesn't have a style — he has instinct.",
    outfit: "Ripped denim jacket over a tank top, fingerless gloves, high-top sneakers, chain-link bracelet.",
    palette: { primary: "#ef4444", secondary: "#2a0e0e", accent: "#ffd6d6", skin: "#a8703f" },
    build: { height: 1.0, width: 0.95 },
    stats: { health: 105, power: 78, defense: 55, speed: 75, jump: 65, combo: 78, special: 60 },
    difficulty: "Easy",
    moves: {
      lightPunch: { name: "Quick Jab", dmg: 5 },
      heavyPunch: { name: "Haymaker", dmg: 12 },
      lightKick: { name: "Shin Kick", dmg: 6 },
      heavyKick: { name: "Curb Stomp Kick", dmg: 12 },
    },
    specials: [
      { name: "Alley Rush", cost: 25, dmg: 13, type: "dash", desc: "A reckless forward charge with a haymaker on arrival." },
      { name: "Bottle Spin", cost: 25, dmg: 11, type: "strike", desc: "A wild spinning backfist — sloppy, but fast." },
      { name: "Street Combo", cost: 35, dmg: 19, type: "combo", desc: "An improvised flurry that somehow always connects." },
    ],
    ultimate: { name: "No Rules Rampage", dmg: 33, desc: "Rex abandons all technique for fifteen relentless seconds of chaos." },
    victoryQuote: "Ha! Didn't even need my good hand.",
    defeatQuote: "Rematch. Right now. I mean it.",
    animStyle: "loose, exaggerated, big wind-ups with attitude",
  },

  jinho: {
    id: "jinho",
    name: "MASTER JIN-HO",
    title: "The Staff Sage",
    age: 58,
    style: "Longstaff Discipline",
    personality: "Wise, unhurried, speaks in short proverbs. Underestimated because of his age — a mistake made only once.",
    backstory: "A retired battlefield instructor who still carries the training staff he's used for forty years. Age slowed his legs, not his timing.",
    outfit: "Simple grey robes, rope sash, worn sandals, a lacquered wooden staff never far from hand.",
    palette: { primary: "#a78bfa", secondary: "#241a3d", accent: "#f3ecff", skin: "#d9a679" },
    build: { height: 1.05, width: 0.8 },
    stats: { health: 95, power: 72, defense: 60, speed: 55, jump: 60, combo: 70, special: 88 },
    difficulty: "Hard",
    moves: {
      lightPunch: { name: "Staff Jab", dmg: 5 },
      heavyPunch: { name: "Staff Crack", dmg: 11 },
      lightKick: { name: "Low Sweep", dmg: 5 },
      heavyKick: { name: "Staff Vault Kick", dmg: 11 },
    },
    specials: [
      { name: "Whirling Guard", cost: 25, dmg: 10, type: "counter", desc: "Spins the staff into a defensive wall, punishing anyone who steps close." },
      { name: "Reaching Strike", cost: 25, dmg: 13, type: "strike", desc: "An extended-range staff thrust." },
      { name: "Elder's Fury", cost: 35, dmg: 17, type: "combo", desc: "A three-strike staff combo finished with a sweeping arc." },
    ],
    ultimate: { name: "Heaven's Staff", dmg: 35, desc: "A single, perfectly timed vertical strike said to end fights before they start." },
    victoryQuote: "Patience wins more fights than speed.",
    defeatQuote: "Even the mountain bends, eventually.",
    animStyle: "measured, long-reach, deliberate spacing",
  },

  pyra: {
    id: "pyra",
    name: "PYRA",
    title: "Volkov's Flame",
    age: 25,
    style: "Plasma-Forged Combat",
    personality: "Intense, dramatic, treats every fight like a performance for an invisible crowd.",
    backstory: "A former industrial welder whose exposure to an experimental plasma rig left her able to channel controlled bursts of heat through her strikes.",
    outfit: "Fitted heat-resistant bodysuit with exposed forearm vents that glow when she powers up.",
    palette: { primary: "#fb923c", secondary: "#3a1607", accent: "#fff1d6", skin: "#c98a5a" },
    build: { height: 0.97, width: 0.85 },
    stats: { health: 85, power: 88, defense: 42, speed: 80, jump: 78, combo: 75, special: 95 },
    difficulty: "Hard",
    moves: {
      lightPunch: { name: "Spark Jab", dmg: 5 },
      heavyPunch: { name: "Flare Cross", dmg: 12 },
      lightKick: { name: "Ember Kick", dmg: 6 },
      heavyKick: { name: "Blaze Crescent", dmg: 13 },
    },
    specials: [
      { name: "Cinder Rush", cost: 25, dmg: 13, type: "dash", desc: "A short burning dash that scorches on contact." },
      { name: "Plasma Bolt", cost: 30, dmg: 15, type: "projectile", desc: "Launches a compact bolt of superheated plasma." },
      { name: "Meltdown Combo", cost: 40, dmg: 20, type: "combo", desc: "A rapid four-hit chain that builds heat with every strike." },
    ],
    ultimate: { name: "Volkov's Inferno", dmg: 38, desc: "Pyra overloads her rig for a single devastating column of flame." },
    victoryQuote: "That's the show. Hope you enjoyed it.",
    defeatQuote: "...Rig's overheating. I'll be back.",
    animStyle: "sharp, glowing wind-ups, trailing heat distortion",
  },

  otto: {
    id: "otto",
    name: "OTTO",
    title: "The Wall Brenner",
    age: 41,
    style: "Counter-Guard Defense",
    personality: "Stoic, methodical, almost never speaks. Watches more than he attacks.",
    backstory: "A former competitive wrestler who reinvented himself as a defensive specialist after an injury. He wins by making opponents beat themselves.",
    outfit: "Reinforced padded vest, wrist guards, cropped hair, a single old scar across one brow.",
    palette: { primary: "#64748b", secondary: "#12171f", accent: "#e6ebf2", skin: "#9c6d47" },
    build: { height: 1.05, width: 1.05 },
    stats: { health: 115, power: 65, defense: 95, speed: 45, jump: 50, combo: 55, special: 60 },
    difficulty: "Medium",
    moves: {
      lightPunch: { name: "Guard Jab", dmg: 4 },
      heavyPunch: { name: "Brace Cross", dmg: 10 },
      lightKick: { name: "Check Kick", dmg: 5 },
      heavyKick: { name: "Wall Kick", dmg: 11 },
    },
    specials: [
      { name: "Iron Guard", cost: 20, dmg: 0, type: "buff", desc: "Braces for a moment, sharply reducing incoming damage." },
      { name: "Punish Grip", cost: 30, dmg: 17, type: "counter", desc: "Catches an incoming attack and answers with a crushing counter." },
      { name: "Backbreaker", cost: 30, dmg: 15, type: "grab", desc: "A close-range grapple slam." },
    ],
    ultimate: { name: "Unbreakable", dmg: 30, desc: "Otto absorbs a full second of punishment, then answers everything at once." },
    victoryQuote: "You spent your energy. I spent none.",
    defeatQuote: "...The wall cracked. It won't happen again.",
    animStyle: "static stance, sudden counters, minimal wasted motion",
  },
};

const CHARACTER_ORDER = ["vela", "thrax", "nyssa", "kobra", "rex", "jinho", "pyra", "otto"];

function getCharacter(id) {
  return CHARACTERS[id];
}
